name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run coverage

      - name: Upload coverage results
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: src/test/coverage
